export type OrderItem = {
  name: string;
  price: string;
  qty: number;
};

export type OrderTimeline = {
  time: string;
  label: string;
};

export type OrderIssue = {
  label: string;
  tone: "warning" | "muted" | "danger";
};

export type Order = {
  id: string;
  shop: string;
  shopAddress: string;
  date: string;
  orderDateLong: string;
  time: string;
  customer: string;
  customerInitials: string;
  isNewCustomer: boolean;
  isUberOne: boolean;
  fulfilmentType: string;
  fulfilmentProvider: string;
  courier: string;
  courierRating: string;
  courierDeliveries: number;
  subtotal: string;
  netPayout: string;
  issues: OrderIssue[];
  items: OrderItem[];
  timeline: OrderTimeline[];
  tab: "active" | "scheduled" | "history";
};

const baseOrders: Order[] = [
  {
    id: "4EF76",
    shop: "Maikhana Adelaide",
    shopAddress: "6 Centre Parade",
    date: "07/06/2026",
    orderDateLong: "7 Jun 2026",
    time: "23:29",
    customer: "Pawankumar A",
    customerInitials: "PA",
    isNewCustomer: true,
    isUberOne: true,
    fulfilmentType: "Delivery",
    fulfilmentProvider: "Uber Eats",
    courier: "ALI",
    courierRating: "89%",
    courierDeliveries: 2165,
    subtotal: "A$50.60",
    netPayout: "A$50.60",
    issues: [],
    items: [
      { name: "Kadai Paneer (V)", price: "A$19.90", qty: 1 },
      { name: "Dal Makhani (V)", price: "A$19.90", qty: 1 },
      { name: "Butter Naan", price: "A$5.90", qty: 1 },
      { name: "Garlic Naan", price: "A$4.90", qty: 1 },
    ],
    timeline: [
      { time: "22:43", label: "Order placed by customer" },
      { time: "22:43", label: "Order confirmed by shop" },
      { time: "23:15", label: "Courier departs" },
      { time: "23:29", label: "Order delivered to customer" },
    ],
    tab: "history",
  },
  {
    id: "17BA3",
    shop: "Maikhana Adelaide",
    shopAddress: "6 Centre Parade",
    date: "07/06/2026",
    orderDateLong: "7 Jun 2026",
    time: "23:18",
    customer: "TANISH C",
    customerInitials: "TC",
    isNewCustomer: false,
    isUberOne: true,
    fulfilmentType: "Delivery",
    fulfilmentProvider: "Uber Eats",
    courier: "KAMRUL",
    courierRating: "92%",
    courierDeliveries: 1840,
    subtotal: "A$44.60",
    netPayout: "A$0.00",
    issues: [
      { label: "1 item wrong", tone: "warning" },
      { label: "Evidence attached", tone: "muted" },
      { label: "Issue charged", tone: "danger" },
    ],
    items: [
      { name: "Butter Chicken", price: "A$22.00", qty: 1 },
      { name: "Jeera Rice", price: "A$12.60", qty: 1 },
      { name: "Mango Lassi", price: "A$10.00", qty: 1 },
    ],
    timeline: [
      { time: "22:50", label: "Order placed by customer" },
      { time: "22:51", label: "Order confirmed by shop" },
      { time: "23:05", label: "Courier departs" },
      { time: "23:18", label: "Order delivered to customer" },
    ],
    tab: "history",
  },
  {
    id: "A942D",
    shop: "Maikhana Adelaide",
    shopAddress: "6 Centre Parade",
    date: "07/06/2026",
    orderDateLong: "7 Jun 2026",
    time: "23:04",
    customer: "Ned L",
    customerInitials: "NL",
    isNewCustomer: false,
    isUberOne: true,
    fulfilmentType: "Delivery",
    fulfilmentProvider: "Uber Eats",
    courier: "TIKSHAN",
    courierRating: "87%",
    courierDeliveries: 920,
    subtotal: "A$32.40",
    netPayout: "A$32.40",
    issues: [],
    items: [{ name: "Veg Thali", price: "A$32.40", qty: 1 }],
    timeline: [
      { time: "22:30", label: "Order placed by customer" },
      { time: "22:31", label: "Order confirmed by shop" },
      { time: "22:50", label: "Courier departs" },
      { time: "23:04", label: "Order delivered to customer" },
    ],
    tab: "history",
  },
  {
    id: "02FBD",
    shop: "Scoop Shoppe",
    shopAddress: "Shop 16A/449 Main N Rd",
    date: "07/06/2026",
    orderDateLong: "7 Jun 2026",
    time: "23:04",
    customer: "Ned L",
    customerInitials: "NL",
    isNewCustomer: false,
    isUberOne: true,
    fulfilmentType: "Delivery",
    fulfilmentProvider: "Uber Eats",
    courier: "TIKSHAN",
    courierRating: "87%",
    courierDeliveries: 920,
    subtotal: "A$20.69",
    netPayout: "A$20.69",
    issues: [],
    items: [
      { name: "Chocolate Sundae", price: "A$12.50", qty: 1 },
      { name: "Vanilla Cone", price: "A$8.19", qty: 1 },
    ],
    timeline: [
      { time: "22:35", label: "Order placed by customer" },
      { time: "22:36", label: "Order confirmed by shop" },
      { time: "22:52", label: "Courier departs" },
      { time: "23:04", label: "Order delivered to customer" },
    ],
    tab: "history",
  },
  {
    id: "B8C21",
    shop: "Scoop Shoppe",
    shopAddress: "Shop 16A/449 Main N Rd",
    date: "06/06/2026",
    orderDateLong: "6 Jun 2026",
    time: "18:42",
    customer: "Priya Joshi",
    customerInitials: "PJ",
    isNewCustomer: true,
    isUberOne: false,
    fulfilmentType: "Pick-up",
    fulfilmentProvider: "Uber Eats",
    courier: "—",
    courierRating: "—",
    courierDeliveries: 0,
    subtotal: "A$25.58",
    netPayout: "A$25.58",
    issues: [],
    items: [{ name: "Family Pack", price: "A$25.58", qty: 1 }],
    timeline: [
      { time: "18:20", label: "Order placed by customer" },
      { time: "18:21", label: "Order confirmed by shop" },
      { time: "18:42", label: "Order picked up by customer" },
    ],
    tab: "history",
  },
];

const extraTemplates: Omit<Order, "id" | "time">[] = [
  {
    shop: "Maikhana Adelaide",
    shopAddress: "6 Centre Parade",
    date: "07/06/2026",
    orderDateLong: "7 Jun 2026",
    customer: "Rahul Mehta",
    customerInitials: "RM",
    isNewCustomer: false,
    isUberOne: true,
    fulfilmentType: "Delivery",
    fulfilmentProvider: "Uber Eats",
    courier: "SAMIR",
    courierRating: "91%",
    courierDeliveries: 1420,
    subtotal: "A$38.20",
    netPayout: "A$38.20",
    issues: [],
    items: [{ name: "Chicken Biryani", price: "A$38.20", qty: 1 }],
    timeline: [
      { time: "21:10", label: "Order placed by customer" },
      { time: "21:11", label: "Order confirmed by shop" },
      { time: "21:35", label: "Courier departs" },
      { time: "21:52", label: "Order delivered to customer" },
    ],
    tab: "history",
  },
  {
    shop: "Scoop Shoppe",
    shopAddress: "Shop 16A/449 Main N Rd",
    date: "07/06/2026",
    orderDateLong: "7 Jun 2026",
    customer: "Emma Wilson",
    customerInitials: "EW",
    isNewCustomer: true,
    isUberOne: false,
    fulfilmentType: "Delivery",
    fulfilmentProvider: "Uber Eats",
    courier: "JAMES",
    courierRating: "94%",
    courierDeliveries: 3100,
    subtotal: "A$15.40",
    netPayout: "A$15.40",
    issues: [],
    items: [{ name: "Strawberry Shake", price: "A$15.40", qty: 1 }],
    timeline: [
      { time: "20:05", label: "Order placed by customer" },
      { time: "20:06", label: "Order confirmed by shop" },
      { time: "20:20", label: "Courier departs" },
      { time: "20:34", label: "Order delivered to customer" },
    ],
    tab: "history",
  },
  {
    shop: "Maikhana Adelaide",
    shopAddress: "6 Centre Parade",
    date: "06/06/2026",
    orderDateLong: "6 Jun 2026",
    customer: "Sonia Patel",
    customerInitials: "SP",
    isNewCustomer: false,
    isUberOne: true,
    fulfilmentType: "Delivery",
    fulfilmentProvider: "Uber Eats",
    courier: "ALI",
    courierRating: "89%",
    courierDeliveries: 2165,
    subtotal: "A$62.10",
    netPayout: "A$62.10",
    issues: [],
    items: [
      { name: "Lamb Rogan Josh", price: "A$24.50", qty: 1 },
      { name: "Garlic Naan", price: "A$4.90", qty: 2 },
      { name: "Raita", price: "A$5.80", qty: 1 },
    ],
    timeline: [
      { time: "19:12", label: "Order placed by customer" },
      { time: "19:13", label: "Order confirmed by shop" },
      { time: "19:40", label: "Courier departs" },
      { time: "20:02", label: "Order delivered to customer" },
    ],
    tab: "history",
  },
  {
    shop: "Scoop Shoppe",
    shopAddress: "Shop 16A/449 Main N Rd",
    date: "06/06/2026",
    orderDateLong: "6 Jun 2026",
    customer: "Liam Chen",
    customerInitials: "LC",
    isNewCustomer: false,
    isUberOne: false,
    fulfilmentType: "Delivery",
    fulfilmentProvider: "Uber Eats",
    courier: "KAMRUL",
    courierRating: "92%",
    courierDeliveries: 1840,
    subtotal: "A$28.90",
    netPayout: "A$28.90",
    issues: [],
    items: [
      { name: "Mint Choc Chip", price: "A$9.50", qty: 2 },
      { name: "Waffle Cone", price: "A$9.90", qty: 1 },
    ],
    timeline: [
      { time: "17:45", label: "Order placed by customer" },
      { time: "17:46", label: "Order confirmed by shop" },
      { time: "18:00", label: "Courier departs" },
      { time: "18:18", label: "Order delivered to customer" },
    ],
    tab: "history",
  },
  {
    shop: "Maikhana Adelaide",
    shopAddress: "6 Centre Parade",
    date: "05/06/2026",
    orderDateLong: "5 Jun 2026",
    customer: "Aisha Khan",
    customerInitials: "AK",
    isNewCustomer: true,
    isUberOne: true,
    fulfilmentType: "Delivery",
    fulfilmentProvider: "Uber Eats",
    courier: "TIKSHAN",
    courierRating: "87%",
    courierDeliveries: 920,
    subtotal: "A$41.80",
    netPayout: "A$41.80",
    issues: [],
    items: [
      { name: "Palak Paneer (V)", price: "A$18.90", qty: 1 },
      { name: "Jeera Rice", price: "A$12.60", qty: 1 },
      { name: "Papadum", price: "A$3.30", qty: 2 },
    ],
    timeline: [
      { time: "12:20", label: "Order placed by customer" },
      { time: "12:21", label: "Order confirmed by shop" },
      { time: "12:45", label: "Courier departs" },
      { time: "13:08", label: "Order delivered to customer" },
    ],
    tab: "history",
  },
  {
    shop: "Scoop Shoppe",
    shopAddress: "Shop 16A/449 Main N Rd",
    date: "05/06/2026",
    orderDateLong: "5 Jun 2026",
    customer: "Noah Brooks",
    customerInitials: "NB",
    isNewCustomer: false,
    isUberOne: false,
    fulfilmentType: "Pick-up",
    fulfilmentProvider: "Uber Eats",
    courier: "—",
    courierRating: "—",
    courierDeliveries: 0,
    subtotal: "A$11.20",
    netPayout: "A$11.20",
    issues: [],
    items: [{ name: "Single Scoop", price: "A$11.20", qty: 1 }],
    timeline: [
      { time: "14:05", label: "Order placed by customer" },
      { time: "14:06", label: "Order confirmed by shop" },
      { time: "14:22", label: "Order picked up by customer" },
    ],
    tab: "history",
  },
  {
    shop: "Maikhana Adelaide",
    shopAddress: "6 Centre Parade",
    date: "04/06/2026",
    orderDateLong: "4 Jun 2026",
    customer: "Mia Santos",
    customerInitials: "MS",
    isNewCustomer: false,
    isUberOne: true,
    fulfilmentType: "Delivery",
    fulfilmentProvider: "Uber Eats",
    courier: "SAMIR",
    courierRating: "91%",
    courierDeliveries: 1420,
    subtotal: "A$55.30",
    netPayout: "A$55.30",
    issues: [],
    items: [
      { name: "Tandoori Chicken", price: "A$24.90", qty: 1 },
      { name: "Butter Naan", price: "A$5.90", qty: 2 },
      { name: "Mango Lassi", price: "A$10.00", qty: 1 },
    ],
    timeline: [
      { time: "20:30", label: "Order placed by customer" },
      { time: "20:31", label: "Order confirmed by shop" },
      { time: "20:55", label: "Courier departs" },
      { time: "21:20", label: "Order delivered to customer" },
    ],
    tab: "history",
  },
  {
    shop: "Scoop Shoppe",
    shopAddress: "Shop 16A/449 Main N Rd",
    date: "04/06/2026",
    orderDateLong: "4 Jun 2026",
    customer: "Oliver Grant",
    customerInitials: "OG",
    isNewCustomer: true,
    isUberOne: false,
    fulfilmentType: "Delivery",
    fulfilmentProvider: "Uber Eats",
    courier: "JAMES",
    courierRating: "94%",
    courierDeliveries: 3100,
    subtotal: "A$33.50",
    netPayout: "A$33.50",
    issues: [],
    items: [
      { name: "Banana Split", price: "A$18.50", qty: 1 },
      { name: "Hot Fudge", price: "A$15.00", qty: 1 },
    ],
    timeline: [
      { time: "18:40", label: "Order placed by customer" },
      { time: "18:41", label: "Order confirmed by shop" },
      { time: "19:00", label: "Courier departs" },
      { time: "19:22", label: "Order delivered to customer" },
    ],
    tab: "history",
  },
  {
    shop: "Maikhana Adelaide",
    shopAddress: "6 Centre Parade",
    date: "03/06/2026",
    orderDateLong: "3 Jun 2026",
    customer: "Zara Ali",
    customerInitials: "ZA",
    isNewCustomer: false,
    isUberOne: true,
    fulfilmentType: "Delivery",
    fulfilmentProvider: "Uber Eats",
    courier: "ALI",
    courierRating: "89%",
    courierDeliveries: 2165,
    subtotal: "A$29.90",
    netPayout: "A$29.90",
    issues: [],
    items: [{ name: "Chole Bhature", price: "A$29.90", qty: 1 }],
    timeline: [
      { time: "13:15", label: "Order placed by customer" },
      { time: "13:16", label: "Order confirmed by shop" },
      { time: "13:40", label: "Courier departs" },
      { time: "14:02", label: "Order delivered to customer" },
    ],
    tab: "history",
  },
  {
    shop: "Scoop Shoppe",
    shopAddress: "Shop 16A/449 Main N Rd",
    date: "03/06/2026",
    orderDateLong: "3 Jun 2026",
    customer: "Ethan Moore",
    customerInitials: "EM",
    isNewCustomer: false,
    isUberOne: false,
    fulfilmentType: "Delivery",
    fulfilmentProvider: "Uber Eats",
    courier: "KAMRUL",
    courierRating: "92%",
    courierDeliveries: 1840,
    subtotal: "A$19.80",
    netPayout: "A$19.80",
    issues: [],
    items: [{ name: "Cookies & Cream", price: "A$19.80", qty: 1 }],
    timeline: [
      { time: "21:00", label: "Order placed by customer" },
      { time: "21:01", label: "Order confirmed by shop" },
      { time: "21:18", label: "Courier departs" },
      { time: "21:35", label: "Order delivered to customer" },
    ],
    tab: "history",
  },
  {
    shop: "Maikhana Adelaide",
    shopAddress: "6 Centre Parade",
    date: "02/06/2026",
    orderDateLong: "2 Jun 2026",
    customer: "Chloe Davis",
    customerInitials: "CD",
    isNewCustomer: true,
    isUberOne: true,
    fulfilmentType: "Delivery",
    fulfilmentProvider: "Uber Eats",
    courier: "TIKSHAN",
    courierRating: "87%",
    courierDeliveries: 920,
    subtotal: "A$47.50",
    netPayout: "A$47.50",
    issues: [],
    items: [
      { name: "Paneer Tikka", price: "A$21.90", qty: 1 },
      { name: "Dal Tadka (V)", price: "A$16.90", qty: 1 },
      { name: "Roti", price: "A$3.70", qty: 2 },
    ],
    timeline: [
      { time: "19:50", label: "Order placed by customer" },
      { time: "19:51", label: "Order confirmed by shop" },
      { time: "20:15", label: "Courier departs" },
      { time: "20:38", label: "Order delivered to customer" },
    ],
    tab: "history",
  },
  {
    shop: "Scoop Shoppe",
    shopAddress: "Shop 16A/449 Main N Rd",
    date: "02/06/2026",
    orderDateLong: "2 Jun 2026",
    customer: "Jack Turner",
    customerInitials: "JT",
    isNewCustomer: false,
    isUberOne: false,
    fulfilmentType: "Delivery",
    fulfilmentProvider: "Uber Eats",
    courier: "SAMIR",
    courierRating: "91%",
    courierDeliveries: 1420,
    subtotal: "A$24.60",
    netPayout: "A$24.60",
    issues: [],
    items: [
      { name: "Rocky Road", price: "A$12.30", qty: 2 },
    ],
    timeline: [
      { time: "16:20", label: "Order placed by customer" },
      { time: "16:21", label: "Order confirmed by shop" },
      { time: "16:38", label: "Courier departs" },
      { time: "16:55", label: "Order delivered to customer" },
    ],
    tab: "history",
  },
];

const extraIds = ["C3D91", "F1A02", "8B774", "D29EC", "5A610", "E84F3", "1C9B8", "7D452", "9E301", "B6A77", "2F8C4", "6D190"];
const extraTimes = ["22:15", "21:48", "20:33", "19:07", "18:22", "17:55", "16:40", "15:18", "14:02", "13:45", "12:30", "11:08"];

const extraOrders: Order[] = extraTemplates.map((template, index) => ({
  ...template,
  id: extraIds[index]!,
  time: extraTimes[index]!,
}));

export const orders: Order[] = [...baseOrders, ...extraOrders];

export function getOrder(id: string) {
  return orders.find((o) => o.id === id);
}
